### ISSUE TITLE
compiling with PGI and CUDA

### ISSUE THREAD

**Issue by ghost** [hypre-space/hypre#323]
Hi,

My name is David and I am working with hypre libraries on some 3D supernova code written in FORTRAN. I've worked with hypre prior and been successful in building the necessary libraries for this code. However, I'm trying to now port this code to GPU and I'm running into issues when I attempt to compile the code. I've been reading the user guides but I seem to be stuck.

**What I am working with:**
OpenMPI-4.0.5 compiled with nvhpc (formerly PGI)
FORTRAN compiled with mpif90 (mpi wrapper for pgfortran)
hdf5-1.12.0 compiled with nvhpc

**Configure options for hypre**
`./configure --enable-fortran --with-MPI --enable-debug --enable-unified-memory --with-device-openmp --prefix=/jet/home/djcalve2/hypre-pgi`

This compiles, but when I attempt to compile my code I am met with errors regarding missing Struct functions 

`undefined reference to `hypre_structgridcreate_'`

I have tried to build with CUDA. I add the `--enable-cuda` option and I set the `CUDA_HOME` environment variable to the home directory of the CUDA install. I get stopped with an error about how `-Wall` is an invalid option for `nvcc`. Setting the CUFLAGS, CFLAGS, and CXXFLAGS to just -g (normally set to -g -Wall) to avoid this issue I'm given another error.

`In file included from /opt/packages/pgi/20.11/Linux_x86_64/20.11/cuda/11.1/include/thrust/detail/config.h:22,
                 from /opt/packages/pgi/20.11/Linux_x86_64/20.11/cuda/11.1/include/thrust/execution_policy.h:23,
                 from _hypre_utilities.hpp:313,
                 from hypre_cuda_utils.c:9:
/opt/packages/pgi/20.11/Linux_x86_64/20.11/cuda/11.1/include/thrust/version.h:80:1: error: unknown type name 'namespace'
 namespace thrust
 ^~~~~~~~~
/opt/packages/pgi/20.11/Linux_x86_64/20.11/cuda/11.1/include/thrust/version.h:81:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 {
 ^
In file included from /opt/packages/pgi/20.11/Linux_x86_64/20.11/cuda/11.1/include/thrust/detail/config/config.h:28,
                 from /opt/packages/pgi/20.11/Linux_x86_64/20.11/cuda/11.1/include/thrust/detail/config.h:23,
                 from /opt/packages/pgi/20.11/Linux_x86_64/20.11/cuda/11.1/include/thrust/execution_policy.h:23,
                 from _hypre_utilities.hpp:313,
                 from hypre_cuda_utils.c:9:
/opt/packages/pgi/20.11/Linux_x86_64/20.11/cuda/11.1/include/thrust/detail/config/cpp_compatibility.h:21:10: fatal error: cstddef: No such file or directory
 #include <cstddef>
          ^~~~~~~~~
compilation terminated.
`

Any insight into what I'm missing during compilation? As a note, I am working on a computer as part of a computing cluster so a lot of access is limited (no sudo, access to some directories blocked, etc.).

Thank you so much for your help!

**Comment by liruipeng** [comment]
Hi @djcalve2 , what is your `CXX`? `-Wall` should be put inside `-Xcompiler "-g -Wall "` with `nvcc`. hypre should do this correctly with `CXX=mpiCC`. Compiling hypre with CUDA 11.1 is fine but I don't have PGI compilers. The `thrust` errors are strange. Also, it should be `--with-cuda`.

**Comment by ghost** [comment]
My CXX is the mpicxx that comes with the PGI compiler:
CXX=/opt/packages/pgi/20.11/Linux_x86_64/20.11/comm_libs/mpi/bin/mpicxx

I've managed to get closer at this point, but still not quite successful. I can compile hypre with the default gcc-compiled versions of mpicxx, mpif90, mpicc, etc. However, my code complains about missing a lot of the ACC functions (specificially, lots of STRUCT complaints). 

However, if I compile with Cuda-11.1 and the pgi versions of mpif90, mpicxx, etc. I fail to compile. It specifically complains that the function "min" is undefined in a .h file, which may be more of a fault of my libs that hypre itself.

```
export CC=/opt/packages/pgi/20.11/Linux_x86_64/20.11/comm_libs/mpi/bin/mpicc
export F90=/opt/packages/pgi/20.11/Linux_x86_64/20.11/comm_libs/mpi/bin/mpif90
export F9X=/opt/packages/pgi/20.11/Linux_x86_64/20.11/comm_libs/mpi/bin/mpif90
export FC=/opt/packages/pgi/20.11/Linux_x86_64/20.11/comm_libs/mpi/bin/mpifort
export CXX=/opt/packages/pgi/20.11/Linux_x86_64/20.11/comm_libs/mpi/bin/mpicxx
export F77=/opt/packages/pgi/20.11/Linux_x86_64/20.11/comm_libs/mpi/bin/mpif77
export CUDA_HOME=/opt/packages/pgi/20.11-mpi4/Linux_x86_64/20.11/cuda/11.1

./configure --enable-fortran --with-MPI --enable-debug --enable-unified-memory --with-cuda --prefix=/jet/home/djcalve2/hypre-pgi
```

This is my environment for the build. On compilation I get the complaint that "min" is referenced but not defined in my CUDA include path when building `csr_spgemm_device_confident.obj`

Thank you for your quick reply and I appreciate your help!

**Comment by victorapm** [comment]
Closing this issue due to inactivity
