### ISSUE TITLE
Recommended CUDA/clang on LC machines

### ISSUE THREAD

**Issue by ptsuji** [hypre-space/hypre#1105]
What's the recommended clang/CUDA compiler set on rzansel? When enabling CUDA and trying to build with clang/ibm-14.0.5 and cuda/11.8.0 (/usr/tce/packages/cuda/cuda-11.8.0/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/tce/packages/clang/clang-ibm-14.0.5/bin/clang++) I get the following errors:

(long build line)
/usr/WS2/tsuji1/ale3d_dev/ale3d/imports/hypre/src/utilities/device_utils.c -o CMakeFiles/HYPRE.dir/utilities/device_utils.c.o

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/type_traits/void_t.h(36): error: namespace "std" has no member "void_t"

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/detail/type_traits/result_of_adaptable_function.h(42): error: namespace "std" has no member "invoke_result_t"

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/detail/type_traits/result_of_adaptable_function.h(42): error: expected a ";"

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/type_traits/logical_metafunctions.h(28): error: namespace "std" has no member "conjunction"

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/type_traits/logical_metafunctions.h(28): error: expected a ";"

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/type_traits/logical_metafunctions.h(32): error: name followed by "::" must be a class or namespace name

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/type_traits/logical_metafunctions.h(36): error: namespace "std" has no member "disjunction"

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/type_traits/logical_metafunctions.h(36): error: expected a ";"

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/type_traits/logical_metafunctions.h(40): error: name followed by "::" must be a class or namespace name

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/type_traits/logical_metafunctions.h(44): error: namespace "std" has no member "negation"

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/type_traits/logical_metafunctions.h(44): error: expected a ";"

/usr/tce/packages/cuda/cuda-11.8.0/nvidia/bin/../targets/ppc64le-linux/include/thrust/type_traits/logical_metafunctions.h(48): error: name followed by "::" must be a class or namespace name

12 errors detected in the compilation of "/usr/WS2/tsuji1/ale3d_dev/ale3d/imports/hypre/src/utilities/device_utils.c".
make[2]: *** [CMakeFiles/HYPRE.dir/build.make:215: CMakeFiles/HYPRE.dir/utilities/device_utils.c.o] Error 1
make[2]: Leaving directory '/usr/WS2/tsuji1/ale3d_dev/ale3d/imports/hypre/src/build-blueos_sierra_clang-relwithdebinfo'
make[1]: *** [CMakeFiles/Makefile2:421: CMakeFiles/HYPRE.dir/all] Error 2
make[1]: Leaving directory '/usr/WS2/tsuji1/ale3d_dev/ale3d/imports/hypre/src/build-blueos_sierra_clang-relwithdebinfo'
make: *** [Makefile:136: all] Error 2
