### ISSUE TITLE
Building with SYCL Fails

### ISSUE THREAD

**Issue by eander2** [hypre-space/hypre#1162]
Build with Intel OneAPI 2024.2 fails with the following error:

par_csr_filter_device.c:182:25: error: use of undeclared identifier 'hypre_popc'; did you mean 'hypre_Log2'?
  182 |          offd_offset += hypre_popc(ballot);
      |                         ^~~~~~~~~~
      |                         hypre_Log2

My configure command is:

./configure --with-sycl --enable-onemklsparse --enable-onemklblas --enable-onemklrand --enable-unified-memory

**Comment by eander2** [comment]
I had tried to build master and release release branch.

**Comment by waynemitchell** [comment]
@eander2 , yes, I am aware that recent changes on the master branch broke the sycl build. Sorry for the inconvenience. For now, you can build the sycl_cleanup branch:
https://github.com/hypre-space/hypre/tree/sycl_cleanup
This should be merged to master soon.
