### PR TITLE
Fix build issues

### PR DESCRIPTION
**Pull request by victorapm**
Fixes build issues:

1. GPU + SuperLU_dist build:

```
src/parcsr_ls/par_amg_setup.c(3158): error: a value of type "void *" cannot be assigned to an entity of type "HYPRE_Solver" (aka "hypre_Solver_struct *")
        ((amg_data)->dslu_solver) = dslu_solver;
```

2. rocm 7.2 build
3. Externally provided rocThrust, see spack CI: https://gitlab.spack.io/spack/spack-packages/-/jobs/19969598#L773
4. Externally provided rocPRIM, see spack CI: https://gitlab.spack.io/spack/spack-packages/-/jobs/19974857#L607
5. Fix portability issue introduced in #1402. See PETSc report: https://gitlab.com/petsc/petsc/-/merge_requests/8978
6. ffs usage in MinGW

### CODE REVIEW

**Comment by victorapm** [comment]
@rfalgout, It seems we are not testing the build with superlu_dist and cuda/rocm enabled. Perhaps we could put it in `machine-tux-spack`

**Comment by prj-** [comment]
Would you consider releasing version 3.1.1 with these fixes?

File: src/config/configure.in [hunk 1]
```diff
@@ -776,7 +776,7 @@ AS_HELP_STRING([--with-MPI-libs=LIBS],
                 --with-MPI-include --with-MPI-libs and --with-MPI-lib-dirs
                 must be used together.]),
 [for mpi_lib in $withval; do
-    MPILIBS+=" -l$mpi_lib"
+    MPILIBS="$MPILIBS -l$mpi_lib"
```
Comment (rfalgout) [inline src/config/configure.in:779]: Just curious.  Does the `+=` not work?

File: src/parcsr_ls/par_amg.h [hunk 2]
```diff
@@ -288,8 +288,8 @@ typedef struct
 
 #ifdef HYPRE_USING_DSUPERLU
    /* Parameters and data for SuperLU_Dist */
-   HYPRE_Int dslu_threshold;
-   HYPRE_Solver dslu_solver;
+   HYPRE_Int      dslu_threshold;
+   void          *dslu_solver;
```
Comment (rfalgout) [inline src/parcsr_ls/par_amg.h:292]: What is the issue here?

File: src/config/configure.in (hunk 1 above)
Comment (victorapm) [reply src/config/configure.in:779]: This is an issue on FreeBSD: `sh` defaults to `ash` which doesn't support `+=` like `bash` does

**Comment by rfalgout** [comment]
> @rfalgout, It seems we are not testing the build with superlu_dist and cuda/rocm enabled. Perhaps we could put it in `machine-tux-spack`

We can test with cuda/rocm on tux?  Do you need me to try something out?

File: src/parcsr_ls/par_amg.h (hunk 2 above)
Comment (victorapm) [reply src/parcsr_ls/par_amg.h:292]: The issues is `hypre_SLUDistCreate` returns a void pointer, which is different than a `HYPRE_Solver`

**Review by rfalgout — APPROVED** [review]

**Comment by victorapm** [comment]
We can test the build at least, I think that would be useful

**Comment by rfalgout** [comment]
> We can test the build at least, I think that would be useful

I suppose we just mimic the lines for the current dsuperlu test.  Did you want to propose a change in `machine-tux-spack.sh` and I can give it a whirl?

**Comment by victorapm** [comment]
Sure, I can implement the changes. Should be a couple of lines. Thanks!

**Comment by victorapm** [comment]
@prj- it looks like there won't be a`v3.1.1` release patch including theses fixes anytime soon. Please, let us know if this is an issue to PETSc. cc @balay

**Comment by balay** [comment]
will use this master snapshot from petsc/main - for now.

File: src/config/cmake/HYPRE_SetupHIPToolkit.cmake [hunk 3]
```diff
@@ -222,24 +222,46 @@ function(find_and_add_rocm_library LIB_NAME)
...
     find_package(${LIB_NAME} REQUIRED)
     if(TARGET roc::${LIB_NAME})
-      message(STATUS "Found target: ${${LIB_NAME}_LIBRARY}")
-      if(NOT ${LIB_NAME_UPPER} STREQUAL ROCTHRUST)
+      message(STATUS "Found target: roc::${LIB_NAME}")
+
+      # Append the library variable that hypre expects.
+      # Do NOT link rocThrust/rocPRIM targets into Hypre: some external packages export HIP-only
+      # link flags (e.g., --hip-link/--offload-arch) that would propagate to downstream pure-C++
+      # targets and break their link steps. We only need theirinclude dirs.
```
Comment (adam-sim-dev) [inline src/config/cmake/HYPRE_SetupHIPToolkit.cmake:230]: their include dirs

Comment (victorapm) [reply src/config/cmake/HYPRE_SetupHIPToolkit.cmake:230]: Thanks for catching, I'll include the typo fix in an upcoming PR
