### ISSUE TITLE
Build fails when HIP enabled

### ISSUE THREAD

**Issue by luspi** [hypre-space/hypre#986]
Hi,

I'm trying to build the latest hypre (pulled from master) with HIP support (specifying `__HIP_PLATFORM_NVIDIA__`), however, it fails to compile at the moment. Here is what I'm doing:

```
$ CFLAGS='-D__HIP_PLATFORM_NVIDIA__' CXXFLAGS='-D__HIP_PLATFORM_NVIDIA__' ./configure --with-hip
(...)

$ make
(...)
mpicc -D__HIP_PLATFORM_NVIDIA__  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.   -I/opt/rocm/include -I/opt/cuda/include         -c device_utils.c -o device_utils.obj
In file included from device_utils.c:10:
_hypre_utilities.hpp:36:4: error: expected specifier-qualifier-list before ‘hypreFunctor_DenseMatrixIdentity’
   36 |    hypreFunctor_DenseMatrixIdentity(HYPRE_Int n, HYPRE_Real *a)
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_hypre_utilities.hpp:65:4: error: expected specifier-qualifier-list before ‘typedef’
   65 |    typedef char value_type;
      |    ^~~~~~~
_hypre_utilities.hpp:213:1: error: unknown type name ‘using’
  213 | using hypre_DeviceItem = void*;
      | ^~~~~
_hypre_utilities.hpp:213:26: error: expected expression before ‘void’
  213 | using hypre_DeviceItem = void*;
      |                          ^~~~
```

GCC: 13.2.1
ROCM: 5.6.1
CUDA: 12.2.0
OpenMPI: 4.5.1
(The system is an up-to-date Arch Linux)

Thank you!

**Comment by victorapm** [comment]
~Oops, this must have been my fault. I'll take a look.~

Thanks for reporting, Lukas!

**Comment by victorapm** [comment]
Quick question: does it work with the latest hypre release (v2.29.0)? 

I've never tried building `--with-hip` but targetting NVIDIA cards. I'm not sure that works. @liruipeng can you confirm?

**Comment by luspi** [comment]
> Quick question: does it work with the latest hypre release (v2.29.0)?

Same problem unfortunately.

> I've never tried building --with-hip but targetting NVIDIA cards. I'm not sure that works.

At least in theory HIP claims to be portable with code working regardless of which backend is chosen. It's of course quite possible that the reality looks a little different...

**Comment by victorapm** [comment]
(Replying via GitHub as well) Sorry if my previous reply caused any confusion. Although many HIP functionalities are able to target NVIDIA cards as well, the way we use HIP in hypre is not supposed to handle that (some parts of the code are ready, but many are not). Instead, we have a specific build option for NVIDIA GPUs (`--with-cuda` via autotools or `-DHYPRE_WITH_CUDA` via cmake).

**Comment by luspi** [comment]
That makes sense. Just to confirm, that with the AMD backend (i.e., an AMD GPU) everything should work just fine, right?

**Comment by luspi** [comment]
(curiously I thought I had hypre with HIP and the NVIDIA backend working in the past, but I guess I must remember wrong)

**Comment by victorapm** [comment]
> AMD backend should work fine, right?

hypre has been tested with the MI series cards (CDNA1, CDNA2). Not 100% sure about the gaming cards (RDNA), but it seems we don't support, see https://github.com/hypre-space/hypre/issues/628#issue-1220762200

> I thought I had hypre with HIP and the NVIDIA backend working in the past

Let me know if you find out that was the case :)

**Comment by liruipeng** [comment]
> > Quick question: does it work with the latest hypre release (v2.29.0)?
> 
> Same problem unfortunately.
> 
> > I've never tried building --with-hip but targetting NVIDIA cards. I'm not sure that works.
> 
> At least in theory HIP claims to be portable with code working regardless of which backend is chosen. It's of course quite possible that the reality looks a little different...

We should have tested the HIP build at least for the previous release. Not sure why it doesn't work here.

**Comment by liruipeng** [comment]
I realized we are talking about the hip build of hypre on NVIDIA GPUs. My previous comment was not correct. We haven’t tried this combination before and I don't think it works for any version of hypre.

**Comment by luspi** [comment]
Ok, thanks for confirming this. I did find a system with an AMD GPU that I have access to (NCSA's Delta), and hypre itself builds just fine with HIP enabled. I then tried to build some of the examples, but am running into some issues there. I added the ROCm/HIP include/lib stuff to the Makefile, but haven't managed to solve this build error yet:

```
$ make ex1
mpicc -g -Wall   -I../hypre/include  -L/opt/rocm/lib -lamdhip64 -lrocsparse -lrocrand  -c ex1.c
mpicc -o ex1 ex1.o   -L../hypre/lib -lHYPRE -lm   -L/opt/rocm/lib -lamdhip64 -lrocsparse -lrocrand
/usr/bin/ld: ../hypre/lib/libHYPRE.a(device_utils.obj): undefined reference to symbol '_ZSt20__throw_length_errorPKc@@GLIBCXX_3.4'
/sw/spack/delta-2022-03/apps/gcc/11.2.0-gcc-8.4.1-fxgnsyr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:129: ex1] Error 1
```

Any ideas what might be missing?

**Comment by victorapm** [comment]
We need to do more work on the examples folder. For now, I'd recommend building the ij driver located at `src/test`

**Comment by luspi** [comment]
Thanks, that ones builds perfectly.

**Comment by victorapm** [comment]
great! let us know if this issue can be closed

**Comment by luspi** [comment]
Oh, yes, it can be closed now.
